spring:
  application:
    name: reada

  datasource:
    url: jdbc:mysql://localhost:8801/reada?useSSL=false&serverTimezone=UTC
    username: root
    password: zayn123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 8802
      password: zayn123
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  mail:
    host: smtp.qq.com
    username: 1563305062@qq.com
    password: ehqklpyegusijhig
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000


server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.zayn.reada.entity
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

sa-token:
  token-name: token
  timeout: 2592000  # 30天
  active-timeout: -1
  is-concurrent: true # 同账号多设备登录
  is-share: false # 共享一个token
  is-log: true # 打印日志
  is-read-header: true # 是否读取header中的token
  token-style: uuid # token风格